name: Publish to PyPI (Trusted Publishing)

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  id-token: write    # REQUIRED for OIDC
  contents: read

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install build backend
        run: |
          python -m pip install --upgrade pip
          pip install build twine

      - name: Build sdist and wheel
        run: python -m build

      - name: Check distributions
        run: twine check dist/*

      - name: Publish to PyPI via OIDC
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          verbose: true
